[General]
__userfile__=true
AlwaysShowTabs=false
AutoSelectionDelay=600
BookmarkedPaths=/home/symbian, /media, /opt/symbian/rom
CloseOnUnmount=true
ConfirmDelete=true
DetailedView=false
EmblemSize=16
FolderViewMode=1
HideSystemFiles=true
IconSize=32
ItemInfo=\0
NoUsbMountWarning=false
OpenInNewTab=false
PathBarButtons=true
PlacesWidth=180
RememberWindowSize=true
SaveSidePaneState=true
ShowFullNames=false
ShowHidden=false
ShowMenuBar=true
ShowSidePane=true
ShowStatusBar=true
SidePaneMode=1
SingleClick=false
SortCaseSensitive=false
SortFolderFirst=true
SortOrder=0
SortRole=0
SplitView=false
ThumbnailLocalFilesOnly=true
ThumbnailMaxFileSize=4096
UsePathBar=true
Wallpaper=/usr/share/backgrounds/symbian-loox-bg.png
WallpaperMode=stretch

[Desktop]
Wallpaper=/usr/share/backgrounds/symbian-loox-bg.png
WallpaperMode=stretch
BgColor=#182028
FgColor=#ffffff
ShadowColor=#000000
ShowHidden=false
SortOrder=0
SortRole=0
Font="Noto Sans,9,-1,5,50,0,0,0,0,0"

[Bookmarks]
C:=/home/symbian
D:=/media
Z:=/opt/symbian/rom
