[General]
__userfile__=true
icon_theme=Symbian-Belle
theme=Symbian-Belle
single_click_activate=false

[Qt]
style=Fusion
font="Noto Sans,9,-1,5,50,0,0,0,0,0"
fixedFont="Monospace,9,-1,5,50,0,0,0,0,0"
doubleClickInterval=400
wheelScrollLines=3
