[General]
__userfile__=true
panels=panel1

[panel1]
alignment=Left
animation-duration=0
background-color=@Invalid()
desktop=0
font-color=@Invalid()
hidpi-icons=false
icon-size=24
line-count=1
names=mainmenu, quicklaunch, taskbar, statusnotifier, tray, mount, battery, volume, clock
opacity=95
panel-size=32
position=Bottom
reserve-space=true
width=100
width-percentage=true

[mainmenu]
type=mainmenu
alignment=Left
custom-icon=/usr/share/icons/Symbian-Belle/symbian-menu.png
use-custom-icon=true
button-text=
shortcut=Super_L

[quicklaunch]
type=quicklaunch
alignment=Left
apps\1\desktop=/usr/share/applications/symbian-files.desktop
apps\2\desktop=/usr/share/applications/symbian-notes.desktop
apps\3\desktop=/usr/share/applications/symbian-calc.desktop
apps\4\desktop=/usr/share/applications/symbian-pkg-manager.desktop
apps\5\desktop=/usr/share/applications/pcmanfm-qt.desktop
apps\size=5

[taskbar]
type=taskbar
alignment=Left
raise-on-desktop-switch=true
show-group-buttons=false
show-only-current-desktop=false
show-only-current-screen=false
show-only-minimized=false
button-style=IconAndText
auto-rotate-text=false
flat-buttons=true

[statusnotifier]
type=statusnotifier
alignment=Right

[tray]
type=tray
alignment=Right

[mount]
type=mount
alignment=Right
icon-size=20

[battery]
type=battery
alignment=Right
show-status=true
show-percentage=true
warning-threshold=15
critical-threshold=5

[volume]
type=volume
alignment=Right
device=default
mixer=Master

[clock]
type=worldclock
alignment=Right
format-date=
format-time=hh:mm
show-date=false
show-seconds=false
auto-rotate-text=false
